# Generated by Django 2.1.2 on 2018-10-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=15)),
                ('dob', models.DateField(max_length=8)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
            ],
        ),
    ]
